name: Test

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  release:
    name: Release build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile source files
        run: scripts\build

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        timeout-minutes: 1
        run: pytest -v .

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: build/**

  debug:
    name: Debug build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile source files
        run: scripts\build debug

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: build/**

  assembly:
    name: Assembly build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile source files
        run: scripts\build assembly

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: assembly
          path: build/**
